---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - export NEXT_PUBLIC_SITE_URL=https://www.lageq.com.br
    - export NODE_ENV=production
    - /bin/npm ci
    - /bin/npm run build
    - /bin/cp -R out/* $DEPLOYPATH
